/**
 * Auto-generated migration map for security-dashboard
 * Maps old API function names to generated @autional/shared/generated/api
 * Generated by: python scripts/generate_api_ts.py --migration security-dashboard
 */
import * as Generated from '@autional/shared/generated/api';

export const getAuditLogs = Generated.adminAuditLogs;
export const getAuditLogDetail = Generated.adminAuditLogsByLogs;
export const getAuditStats = Generated.adminAuditStats;
export const verifyAuditChain = Generated.adminAuditVerificationsPost;
export const getVerificationResults = Generated.adminAuditVerifications;
export const getHashChain = Generated.adminAuditHashchainByHashchain;
export const getArchiveStatus = Generated.adminAuditArchiveStatus;
export const exportAuditLogs = Generated.adminAuditExportPost;
export const getAnomalies = Generated.adminAuditAnomalies;
export const updateAnomalyStatus = Generated.adminAuditAnomaliesStatusByAnomaliesPut;
export const getAnomalyById = Generated.adminAuditAnomaliesByAnomalies;
export const getAnomalyTimeline = Generated.adminAuditAnomaliesTimelineByAnomalies;
export const getRelatedAnomalies = Generated.adminAuditAnomaliesRelatedByAnomalies;
export const assignAnomaly = Generated.adminAuditAnomaliesAssignByAnomaliesPost;
export const addAnomalyComment = Generated.adminAuditAnomaliesCommentByAnomaliesPost;
export const getComplianceStatus = Generated.complianceStatus;
export const getComplianceSelfScore = Generated.adminComplianceTenantsSelfScore;
export const getDSARs = Generated.adminComplianceGdprDsar;
export const getDSARById = Generated.adminComplianceGdprDsarByDsar;
export const getDSARStatus = Generated.complianceGdprDsarStatusByDsar;
export const updateDSAR = Generated.adminComplianceGdprDsarByDsarPut;
export const getBreachNotifications = Generated.adminComplianceBreachNotifications;
export const updateBreachNotification =
	Generated.adminComplianceBreachNotificationsByBreachNotificationsPut;
export const getEvidence = Generated.adminComplianceEvidence;
export const getEvidenceById = Generated.adminComplianceEvidenceByEvidence;
export const getRetentionPolicies = Generated.adminComplianceRetentionPolicies;
export const getISOControls = Generated.adminComplianceIso27001Controls;
export const getSOXControls = Generated.adminComplianceSoxItgc;
export const getPenTestReports = Generated.adminCompliancePenetrationTestReports;
export const getAuditFindings = Generated.adminComplianceAuditFindings;
export const getAuditFindingById = Generated.adminComplianceAuditFindingsByAuditFindings;
export const updateAuditFinding = Generated.adminComplianceAuditFindingsByAuditFindingsPut;
export const getSessions = Generated.sessions;
export const getActiveSessionCount = Generated.adminSessionsActiveCount;
export const terminateSession = Generated.sessionsBySessionsDelete;
export const getSecurityReport = Generated.adminAuditReportsSecurity;
export const getComplianceReport = Generated.adminAuditReportsCompliance;
export const getExportJobs = Generated.adminAuditExportJobs;
export const downloadExport = Generated.adminAuditExportDownloadByExport;
export const createExportJob = Generated.adminAuditExportPost;
export const getMerkleRoot = Generated.adminAuditMerkleRoot;
export const getMerkleProof = Generated.adminAuditMerkleProof;
export const getRetentionPolicy = Generated.adminAuditRetentionPolicy;
export const updateRetentionPolicyAdmin = Generated.adminAuditRetentionPolicyPut;
export const getSiemConnectors = Generated.adminAuditSiemConnectors;
export const createSiemConnector = Generated.adminAuditSiemConnectorsPost;
export const updateSiemConnector = Generated.adminAuditSiemConnectorsByConnectorsPut;
export const deleteSiemConnector = Generated.adminAuditSiemConnectorsByConnectorsDelete;
export const testSiemConnector = Generated.adminAuditSiemConnectorsTestByConnectorsPost;
export const triggerArchive = Generated.adminAuditArchivePost;
export const getAlerts = Generated.adminAuditAlerts;
export const getAlertById = Generated.adminAuditAlertsByAlerts;
export const assignAlert = Generated.adminAuditAlertsAssignByAlertsPost;
export const updateAlertStatus = Generated.adminAuditAlertsStatusByAlertsPut;
// @generated-api-exempt: BFF gateway composite endpoints — registered at
// /bff/gateway/api/v1/security on gateway engine (JWT required). apiClient
// prepends /bff, so use raw fetch with the Bearer token (same pattern as
// SSEEventStream) to reach /bff/gateway/api/v1/security/users.
// Response keys are snake_case (raw fetch bypasses apiClient interceptor), so apply
// camelCaseKeys to match the interceptor behavior expected by the pages.
export const getSecurityUserProfile = async (userId: string) => {
	const token = (await import('@autional/shared')).getAccessToken();
	const { camelCaseKeys } = await import('@autional/shared');
	const res = await fetch(`/bff/gateway/api/v1/security/users/${userId}/profile`, {
		headers: { Authorization: `Bearer ${token}`, Accept: 'application/json' },
	});
	if (!res.ok) throw new Error(`HTTP ${res.status}`);
	const body = await res.json();
	return camelCaseKeys(body.data);
};
// @generated-api-exempt: BFF gateway composite endpoints — registered at
// /bff/gateway/api/v1/security on gateway engine (JWT required)
// S-72③：分页透传（网关 GetUserSecurityTimeline 支持 page/page_size，响应附 events_total）
export const getSecurityUserTimeline = async (
	userId: string,
	params?: { page?: number; pageSize?: number },
) => {
	const token = (await import('@autional/shared')).getAccessToken();
	const { camelCaseKeys } = await import('@autional/shared');
	const qs = new URLSearchParams();
	if (params?.page) qs.set('page', String(params.page));
	if (params?.pageSize) qs.set('page_size', String(params.pageSize));
	const query = qs.toString();
	const res = await fetch(
		`/bff/gateway/api/v1/security/users/${userId}/timeline${query ? `?${query}` : ''}`,
		{
			headers: { Authorization: `Bearer ${token}`, Accept: 'application/json' },
		},
	);
	if (!res.ok) throw new Error(`HTTP ${res.status}`);
	const body = await res.json();
	return camelCaseKeys(body.data);
};
// @generated-api-exempt: compliance 状态 admin twin（W3-C 新增，security_admin 可达）尚未进入
// shared 生成物，下轮重生成后可迁回 Generated.*。raw fetch 绕过 apiClient，需手动对齐其
// /bff 前缀 + 信封解包 + camelCase 行为（与上方 getSecurityUserProfile 同模式）。
export const getAdminComplianceStatusRaw = async () => {
	const token = (await import('@autional/shared')).getAccessToken();
	const { camelCaseKeys } = await import('@autional/shared');
	const res = await fetch('/bff/compliance/api/v1/admin/compliance/status', {
		headers: { Authorization: `Bearer ${token}`, Accept: 'application/json' },
	});
	if (!res.ok) throw new Error(`HTTP ${res.status}`);
	const body = await res.json();
	return camelCaseKeys(body.data);
};
export const getNotificationPlatformStats = Generated.adminNotificationsPlatformStats;
export const getNotificationReadReport = Generated.notificationsReadReport;
export const getCommunicationPlatformStats = Generated.adminCommunicationPlatformStats;
export const getAdminAgents = Generated.adminAgents;
export const getAdminRobots = Generated.adminRobots;
export const getAdminIots = Generated.adminIots;

// Agent mutations
export const createAgent = Generated.adminAgentsPost;
export const getAgentById = Generated.adminAgentsByAgents;
export const updateAgent = Generated.adminAgentsByAgentsPut;
export const deleteAgent = Generated.adminAgentsByAgentsDelete;

// Robot mutations
export const createRobot = Generated.adminRobotsPost;
export const getRobotById = Generated.adminRobotsByRobots;
export const updateRobot = Generated.adminRobotsByRobotsPut;
export const deleteRobot = Generated.adminRobotsByRobotsDelete;
export const commissionRobot = Generated.adminRobotsCommissionByRobotsPost;
export const decommissionRobot = Generated.adminRobotsDecommissionByRobotsPost;
export const issueIntentToken = Generated.adminRobotsIntentByRobotsPost;
export const revokeIntentToken = Generated.adminRobotsIntentRevokeByRobotsPost;

// Device mutations
export const createDevice = Generated.adminIotsPost;
export const getDeviceById = Generated.adminIotsByIots;
export const deleteDevice = Generated.adminIotsByIotsDelete;
export const pairDevice = Generated.iotsPairPost;
export const unpairDevice = Generated.iotsByIotsDelete;
export const transferDevice = Generated.iotsTransferByIotsPost;

// NHI Policy
export const getNhiPolicy = Generated.adminPoliciesNhi;
export const updateNhiPolicy = Generated.adminPoliciesNhiPut;
export const fetchGatewayStatusRaw = async () => {
	const res = await fetch('/ready');
	// S-02（fix-security-w5）：环境未把 /ready 接到网关时（如 SPA fallback 返回 index.html，
	// 200 text/html），res.json() 抛 SyntaxError 且报错无诊断价值——前置 content-type 守卫，
	// 抛带诊断信息的错误交给卡片错误态 + 重试。
	const contentType = res.headers.get('content-type') || '';
	if (!contentType.includes('application/json')) {
		throw new Error(`/ready: unexpected content-type "${contentType || 'none'}" (HTTP ${res.status})`);
	}
	// 注意：网关 /ready 不健康时返回 503，但 body 仍是 JSON（checks/checks_latency）——
	// 须照常解析渲染服务红点，不可按 !res.ok 抛错（那是「服务不健康」不是「接口失败」）。
	return res.json();
};
